version: '3.8'

services:
  lil-postgres:
    image: postgres
    container_name: lil-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

  activemq:
    image: rmohr/activemq
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    restart: unless-stopped